[project]
name = "ocelescope-module-ocpn-editor"
version = "0.1.0"
readme = "README.md"
description = "An OCPN Editor"
authors = [{ name = "Uy Sa Huynh" }]
requires-python = ">=3.11"
dependencies = [
  "ocelescope-backend>=0.8.0",
]

[project.entry-points."ocelescope_backend.modules"]
ocpnEditor = "ocelescope_module_ocpn_editor.module:OCPNEditor"

[build-system]
requires = ["uv_build>=0.9.26,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
package = true
