name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Build and push multi-arch images
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7
        env:
          VERSION: ${{ github.event.release.tag_name || 'latest' }}
          REPO: ghcr.io/${{ github.repository }}
        with:
          source: .
          files: ./docker-bake.hcl
          push: true
          set: |
            *.platform=linux/amd64,linux/arm64
